### ISSUE TITLE
Feedback on Milestone 1

### ISSUE THREAD

**Issue by Nazliozum** [UBC-MDS/DSCI_522_Income_Prediction#29]
@olivia-lin @ksm45 
You have made lots of great additions to your analysis for this milestone. 

Here are some remaining issues:

- [x] Add a link to your report on the main readme 
- [x] Add instructions to run your analysis on main readme
- [x] Add dependencies with their version information on the readme
- [x] Fix the broken links in the Dataset section on your readme
- [ ] Try to change the proposal structure on the main readme. I can also suggest not to use future tense in your statements. Same thing applies for your report.
- [x] Add figure numbers to your plots in the report. Try to resize them as some figures are too big. Try to elaborate on the visualizations. You should have some explanations as to what the figures are telling us.
- [x] Decrease bullet points in your report. You can definitely write explanations in paragraph format for some sections such as the Limitations and Future Directions sections.
- [x] You have a References section, but I don't see any references. Either delete the section or add your sources.

**Suggestions:**

- You can include a flow chart/dependency diagram on your readme.

**Comment by ksm45** [comment]
added dependencies

**Comment by olivia-lin** [comment]
added link for final report in readme

**Comment by olivia-lin** [comment]
Added instructions to run our analysis on main readme

**Comment by olivia-lin** [comment]
Changed plot size and added plot title

**Comment by olivia-lin** [comment]
Reference section: we already had our references in rmd file when we submitted for milestone 1 (Mani did it), the thing we forgot to push is the updated md file

**Comment by olivia-lin** [comment]
Replace the bullet points in the report
